name: nanobanana-pro

services:
  postgres:
    image: postgres
    container_name: nanobanana-pro-postgres
    environment:
      POSTGRES_DB: nanobanana-pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - nanobanana-pro_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nanobanana-pro_postgres_data:
